apiVersion: v1
kind: Pod
metadata:
  generateName: restart-kubelet-pod-
spec:
  restartPolicy: Never
  containers:
    - command:
        - sleep
        - "10"
      image: registry.redhat.io/openshift4/ose-must-gather:latest
      name: restart-kubelet
      terminationMessagePolicy: FallbackToLogsOnError